### ISSUE TITLE
Assign cohort trigger not doing anything

### ISSUE THREAD

**Issue by emmafsp** [catalyst/moodle-tool_trigger#143]
We have a workflow set up to assign users to a cohort on account creation. The trigger appears to be registering but the step isn't working. 

The step is simply set to assign users to cohort, with the relevant cohort id. 

It says the event has triggered but the user doesn't get added. This is regardless of whether the account is created by an admin or as a user creating a new account (we have email-based self registration on). 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/86419385/123297748-c61dce80-d50f-11eb-91fd-e32c75fb8567.png)

**Comment by danmarsden** [comment]
Hi there - the cohort step expects the id number of the cohort - not the "name" to be used in that form - you need to work out what the value in the "id" field is for that cohort rather than using "cohort1" in that field for this to work.

There's definitely some room for improvement to the cohort step to allow other parameters to be used in there though - please get in touch if you would like to fund improvements and of course pull requests are always welcome too!

**Comment by emmafsp** [comment]
Ah that's great, yes that's it! It is now triggering and adding a user to the cohort. Only issue is it's adding the admin to the cohort, as the person that created the account, not the new account itself. If the user creates an account for themselves, it doesn't do anything. I'm guessing I need to find the right userid now.
