### ISSUE TITLE
gdpr - table tool_trigger_events

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_trigger#20]
comment from Victor during review:

Personal data can be stored in table tool_trigger_events and exported to external locations, so metadata provider should be implemented accordingly.

--
I think we've sorted the external location stuff, but I don't think we've included metadata for tool_trigger_events. it is transient for succesful events, but for failures we may be retaining user data as we store the full event that was triggered and we are only clearing succesful events from the log (from memory)

**Comment by agwells** [comment]
Yep, the privacy metadata I wrote was based on the assumption that the tool_trigger_events table was transient. But looking at the code in `classes/task/cleanup.php` now, I see it was indeed written to only delete events from successfully run workflows. (Although currently, due to my refactoring of the workflow status constants in `classes/task/process_workfllows.php`, it no longer actually does this! I'll file a separate bug about that.)

Unfortunately, due to that pesky unspecified $event->other field, there's no 100% guaranteed way to find all event records relating to a particular user. So if we want to be really thorough, we should just go ahead and clear out the failed events as well. Or maybe just blank out their "other" field? Although that would reduce their usefulness for debugging.

If it's okay to be a little less rigorous, we could check the columns "objectid" (when objecttable = usr), userid, relateduserid, and realuserid, and look for "other" records that contain fields that are likely to be a user id.

**Comment by agwells** [comment]
Okay, since our `tool_trigger_event` table is using the same table structure and serialization code as `logstore_standard_log`, I took a look at what the `standard` logstore plugin does for privacy.

It turns out it has a privacy provider which handles deletion and export for its log table (which ours is a clone of), so we should be good if we just copy that logic. It is conveniently bundled up into a trait, `\tool_log\local\privacy\moodle_database_export_and_delete`.

> Moodle database: export and delete trait.
>
> This is to be used with logstores which use a database and table with the same columns
> as the core plugin 'logstore_standard'.

That's us!

**Comment by agwells** [comment]
Done
