### ISSUE TITLE
Personal data exported

### ISSUE THREAD

**Issue by vmdef** [catalyst/moodle-tool_trigger#22]
Feel free to close this issue if it is not relevant. This plugin allows to export personal data of  any user in the system to another external system (HTTP post, email, ...), so I think it's important to add the RISK_PERSONAL bitmask to the capability and to implement the correponding metadata provider(https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location).

**Comment by agwells** [comment]
Hi @vmdef, I've pushed up a commit that adds `RISK_PERSONAL` to the plugin's `tool/trigger:manageworkflows` capability. I also added `RISK_SPAM`, because you can configure a workflow to send out emails to arbitrary email addresses.

A couple of days ago I also added metadata providers to indicate that the plugin can send out users' personal data via HTTP POST and emails. (I think that's not in the version that's in the Moodle plugin repo yet, though.) So currently the privacy listing looks like this:

* **tool_trigger_events** (database_table): Data from monitored Moodle events
  * eventname: The event name
  * userid: The ID of the user who triggered this event
  * relateduserid: The ID of a user related to this event
  * anonymous: Whether the event was flagged as anonymous
  * other: Additional information about the event
  * timecreated: The time at which the event occurred
  * origin: The origin of the event
  * ip: The IP address used at the time of the event
  * realuserid: The ID of the real user behind the event, when masquerading a user.
* **email_action_step** (external_location): This plugin may be configured to send emails containing data from Moodle. It does not store data locally.
  * tool_trigger_events: Data from monitored Moodle events
  * user_lookup_step: Personal data about users, such as usernames, names, email addresses, etc.
  * course_lookup_step: Data about courses, including id, course name, start and end dates, etc.
* **http_post_action_step** (external_location): This plugin may be configured to send HTTP requests to external addresses, containing data from Moodle. It does not store data locally.
  * tool_trigger_events: Data from monitored Moodle events
  * user_lookup_step: Personal data about users, such as usernames, names, email addresses, etc.
  * course_lookup_step: Data about courses, including id, course name, start and end dates, etc.

**Comment by vmdef** [comment]
Brilliant!! I haven't think about SPAM. In the repo I've seen part of the privacy implementation, but your approach is right. Thanks for taking your time adding this modifications.
