### ISSUE TITLE
add new manageworkflow.php file for deleting and duplicating of workflows.

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_trigger#3]
when you have added a number of workflows, you should be able to delete or duplicate existing workflows by clicking the delete/duplicate icons on the main index.php page:

(similar to tool/monitor/managerules.php)
![mangetriggers](https://user-images.githubusercontent.com/362798/39661565-a93f3a6e-50a7-11e8-8c99-c02161a7f53c.png)

**Comment by agwells** [comment]
Okay, I've pushed up the script for this. Can you take a look at it @danmarsden and see if I've missed anything? It's been a long time since I've made a Moodle page!

**Comment by agwells** [comment]
Should I delete all of a workflow's entries in the tool_trigger_queue table, when the workflow is deleted?

**Comment by danmarsden** [comment]
looks good - made a minor change to manageworkflow.php to remove a line that wasn't needed, I also notice you're loading the name/description from the json data rather than from the steps ->name field etc but I can't think of a reason why this will be a problem right now.
I've also added a commit to delete the tool_trigger_queue table entries too - this can be closed - thanks!

**Comment by danmarsden** [comment]
just re-opened because it looks like duplicating a workflow isn't duplicating the steps for that workflow - probably a simple fix.

**Comment by agwells** [comment]
> just re-opened because it looks like duplicating a workflow isn't duplicating the steps for that workflow - probably a simple fix.

Cheers, that was a bug on my part. I've pushed up a fix. :)

>  I also notice you're loading the name/description from the json data rather than from the steps ->name field etc but I can't think of a reason why this will be a problem right now.

Do you mean the code in `\tool_trigger\edit_form::definition_after_data()` that displays the table of steps? That actually is using the columns from the DB, by a sort of roundabout process of DB -> PHP -> JSON -> PHP -> HTML:

1. I click on "edit workflow" icon
2. `edit.php` calls `\tool_trigger\workflow_process::to_form_defaults()`, which calls `\tool_trigger\workflow_process::encode_steps_to_json_for_form()`, which merges together the DB columns from `mdl_tool_trigger_steps` and the deserialized JSON from `mdl_tool_trigger_steps.data`, and converts it into the same data structure as the modal form
3. `edit.php` puts that JSON as the default value of the `stepjson` hidden form field
4. `\tool_trigger\edit_form::definition_after_data()` retrieves the value of `stepjson`, deserializes it back into PHP, and uses it to display the table.

I did it that way so that it could use the same code to render the table whether you've just clicked on "edit", or if we're re-rendering after failed validation in which case `stepjson` may contain JSON added by the modal form. (I think that's the right way to do it? It's been a while.)

I did notice, though, that in `\workflow_process::encode_steps_to_json_for_form()`, that I'd used `array_merge()` in such a way that, if there were fields in `tool_trigger_steps.data`'s JSON that had the same name as a named column of `tool_trigger_steps`, the value from the JSON would override the value from the named column. So I've swapped those around so that now the named column would take precedence. Though, it looks like currently the values with the same names as the columns are removed from the JSON, so it shouldn't matter much. :)

**Comment by danmarsden** [comment]
cool - makes sense thanks!
