### ISSUE TITLE
Improve storage of tool_trigger_events records

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_trigger#5]
tool_trigger_events is basically a copy of the tool_monitor_events table but we need to retain more information about the events for the trigger plugin.

We should have a new userid field that stores the userid that was loggedin (realuserid if using loggedinas functions)

I'd also like to see a new "data" style field that contains everything else from the event so that we can include any information from the actual event that was triggered in the workflow steps.

**Comment by danmarsden** [comment]
extra info should be included in the event that is passed when executing the workfow step:
https://github.com/catalyst/moodle-tool_trigger/blob/master/classes/task/process_workflows.php#L113

**Comment by agwells** [comment]
Done! I copied the logic from the core `logstore_standard` plugin, for serializing and restoring events. Where possible I re-used core code, specifically the `\tool_log\helper\buffered_writer` trait for serializing the events. (Unfortunately the corresponding `\tool_log\helper\reader` trait doesn't contain the corresponding deserialization logic, so I had to copy that out of `\logstore_standard\log\store::get_log_event_data()`).

One limitation to this approach, is that [Moodle Event 2](https://docs.moodle.org/dev/Event_2) API  events can have state in "record snapshots", which is *not* serialized into the logs. For the most part we can just work around this; `\core\event\base::get_record_snapshot()` will fall back to querying the DB. The biggest downside is for deletion events, because Event 2 deletion events are recommended to take a record snapshot of the deleted object but not serialize it.

If this turns out to be a problem, we could maybe check the event for "objecttable" and "objectid" values, and then retrieve and serialize the record there ourselves.
