### ISSUE TITLE
Lookup steps

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-tool_trigger#6]
A lookup is a way of adding extra information to the $eventdata passed to subsequent steps that is not included in the actual event that was triggered. For example user firstname/lastname/email or Course shortname/fullname etc.

Can you look at a way to implement some initial simple lookups for user fullname/email etc that gets added to the $event stdclass passed to subsequent steps?
maybe something like:
if (!empty($previoiusstepresult->eventdata)) 
add eventdata to exsiting $event

hopefully that makes sense?

**Comment by agwells** [comment]
Hm, here's where we start to hit one of the deep problems of this plugin. How do we want to let the user specify what fields to access / add ?

This is made more difficulty, by the fact that Moodle 2 events are not programmatically self-describing, not fully. There are a bunch of standard event properties (mostly optional), and there's the fully class-custom "other" field, which is an associative array potentially containing nested arrays. It's a coding standard to include a human-readable description of the "other" field contents, but since that's just human-readable, it's not guaranteed to be parseable in a useful way. And, of course, our lookup and trigger steps can add additional custom fields to $previousstepresult.

For now, to get to a minimum viable product, I guess I'll start by having the user just type in the fieldname by hand, and then we can check for a scalar field with a matching name, in $previousstepresults, $event->other, and the standard event fields. And then perhaps also display a help field with the names of the standard fields, the event's human-readable description (which should describe its "other" fields), and maybe any stuff added by previous steps.

**Comment by agwells** [comment]
I did some looking into lightweight, sandboxed scripting languages that we might use, to allow more complex user logic. Some possibilities:

1.~~Moodle "calculated question type" equation syntax.~~ No support for arrays.
2. *SQLite*: Insert the workflow event data into a temporary sqlite database, and let the user write queries against it. This initially looked like a very promising possibility, especially because PHP includes the SQLite JSON extension! ... But unfortunately SQLite's core functionality has an "attach database()" query that lets you access arbitrary SQLite DB's anywhere on the filesystem. Additionally, there are "pragma" settings that can also impact the filesystem. The PHP sqlite extension provides no way to disable these (even if you set the DB connection to "read only"). Potentially we could try filtering "attach" and "pragma" out of the user's queries, but that's always difficult to do securely.
3. *Mustache templates*: A possible way to deal with array values? Provide an array field as the context, and save the output as a string in a new field. Or maybe JSON-decode the output, to let the user transform one JSON-encoded array into a different JSON array.
4. Escribunto: This is a Mediawiki plugin for executing sandboxed Lua scripts, via PHP.
5. The Lua and V8 (JS) extensions for PHP.
6. Various other "scripting interpreter in PHP" libraries I found in packagist: https://packagist.org/?query=interpreter https://packagist.org/?query=scripting

**Comment by agwells** [comment]
After discussion with Dan, for now we'll stick to just simple output templating, like `str_replace('{fieldname}', ...)`. There are a few different Moodle plugins that have settings with substitution systems like this... but no one standard syntax for it. :) Badge messages use `%tag%`, the database assignment uses `##tag##`, the calculated question type uses `{tag}`, etc. So we'll just go with `{}` for now.

I may also do some "namespacing" of the tags available. For instance, make the fields of "other" data available as e.g. "other.field1", "other.field2", etc.

**Comment by agwells** [comment]
Okay, I've pushed up the user_lookup_step class. The workflow author indicates which event field to get the user ID from (it defaults to "userid", which is the standard event field), and the lookup pulls all the user fields for that user, and adds them to the workflow data.

I also added a trigger class that just does a var_dump() to the cron logs, to test it out.

**Comment by danmarsden** [comment]
awesome! - I've been playing with an e-mail trigger today, will add that later today as well.

**Comment by FMCorz** [comment]
I'm not too sure what this plugin is about or how it's used, but I'm happy to assist with using _shortcodes_ if it turns out to be answering your needs.

**Comment by danmarsden** [comment]
Thanks @FMCorz - it's similar to the tool_monitor plugin but allows an external action to occur on each event - eg e-mail/http post etc. 
The action allows for variables from the events to be included in the url params/text of email etc.
bit more context here:
https://github.com/catalyst/moodle-tool_trigger/wiki

Unlikely we'll implement your shortcodes plugin in the current release, but I wanted to flag it because it might make for some nice usability improvements in a future release.

**Comment by FMCorz** [comment]
Oh, I've come across this idea in the past, that's a cool plugin. I doubt shortcodes would be suited for this as you're looking at context specific placeholders defined by the event data. _Shortcodes_ are mostly designed to be used by end-users when writing content, anywhere. Although, you could probably write a shortcode that's aware of the event being processed by using some sort of global.

Thanks for flagging it!
